### ISSUE TITLE
encode! bug

### ISSUE THREAD

**Issue by jcoyne** [ruby-rdf/rdf-n3#16]
I have a string like this: `קליפורניה` it's encoding is not specified, so ruby says it is `ASCII_8BIT`, however it's actually UTF-8.

When we try to run `.encode!(Encoding::UTF_8)`, this causes an encoding error: 
```
"קליפורניה".force_encoding(Encoding::ASCII_8BIT).encode!(Encoding::UTF_8)
Encoding::UndefinedConversionError: "\xD7" from ASCII-8BIT to UTF-8
```
That code is happening here: https://github.com/ruby-rdf/rdf-n3/blob/develop/lib/rdf/n3/reader/parser.rb#L168

The correct thing to do is to force the encoding to UTF_8:

```
"קליפורניה".force_encoding(Encoding::ASCII_8BIT).force_encoding(Encoding::UTF_8)
=> "קליפורניה"
```

I'm not sure why you made this change: https://github.com/ruby-rdf/rdf-n3/commit/403e0e38fd781951ec930deace5f0dcd6f858405 but you may want to consider reverting it.

**Comment by gkellogg** [comment]
Hmm, unfortunate. This is probably in a couple of other gems too. Have you tried using rdf-turtle?

**Comment by jcoyne** [comment]
@gkellogg I have not checked any of the other parsers. This is only coming to light from work I'm doing with rdf-marmotta.

**Comment by gkellogg** [comment]
@jcoyne See if this solves your problem, and reopen if not.
