### ISSUE TITLE
Error when parsing shortened iri containing digits

### ISSUE THREAD

**Issue by ArthurWD** [ruby-rdf/rdf-n3#19]
I'm getting errors when parsing shortened iri's containing digits.

This works:
```
RDF::Graph.new.from_n3("@prefix example: <https://example.com/>.\n\nexample:subject example:predicate example:object.")
```

But this doesn't:
```
RDF::Graph.new.from_n3("@prefix example: <https://example.com/>.\n\nexample:subject example:predicate example:1.")
```

It raises the following error:
```
RDF::ReaderError: Found '0' when parsing a objecttail. expected ",","object","objecttail" | 
```

Is this an invalid statement or is it an error in the parser?

**Comment by gkellogg** [comment]
It can be a but challenging to parse the [N3 Grammar](https://www.w3.org/2000/10/swap/grammar/n3.n3) referenced from the [note](https://www.w3.org/TeamSubmission/n3/), but this is the `qname` pattern:

```turtle
qname 		cfg:matches  	"(([A-Z_a-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\U00010000-\U000effff][\\-0-9A-Z_a-z\u00b7\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u037d\u037f-\u1fff\u200c-\u200d\u203f-\u2040\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\U00010000-\U000effff]*)?:)?[A-Z_a-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\U00010000-\U000effff][\\-0-9A-Z_a-z\u00b7\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u037d\u037f-\u1fff\u200c-\u200d\u203f-\u2040\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\U00010000-\U000effff]*";
		cfg:canStartWith 	"a", "_", ":".  # @@ etc unicode
```

A `qname` is defined into `prefix` and `name` parts, and a name cannot begin with a digit. The relevant part of the regular expression is `[A-Z_a-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\U00010000-\U000effff][\\-0-9A-Z_a-z\u00b7\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u037d\u037f-\u1fff\u200c-\u200d\u203f-\u2040\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\U00010000-\U000effff]*`.

Note, however, that the [Turtle production for `PN_LOCAL`](https://www.w3.org/TR/turtle/#grammar-production-PN_LOCAL) does allow for a leading digit.

```bnf
[168s] PN_LOCAL                       ::= ( PN_CHARS_U | ':' | [0-9] | PLX )
                                          ( ( PN_CHARS | '.' | ':' | PLX )* 
                                            ( PN_CHARS | ':' | PLX ) ) ?
```

**Comment by ArthurWD** [comment]
Okay thanks, in that case it seems like the serializer we use is broken.
