### ISSUE TITLE
Lists not correctly marked as seen

### ISSUE THREAD

**Issue by ArthurWD** [ruby-rdf/rdf-n3#20]
https://github.com/ruby-rdf/rdf-n3/blob/aedfbb9cdfc9a638c7fca78746e9df49f2c86ac2/lib/rdf/n3/writer.rb#L333

Should be 

```
seen[st.object] = true if @lists.has_key?(st.object) 
```

Same issue is in the turtle gem. Do you want me to make a PR or will you fix it?

**Comment by gkellogg** [comment]
Yes, please. A test which fails as is, and passes with the fix would be useful too.
