### ISSUE TITLE
Go

### ISSUE THREAD

**Issue by Nabin2469** [ruby-rdf/rdf-n3#24]
Go on              Go

_Originally posted by @Nabin2469 in https://github.com/ruby-rdf/rdf-n3/pull/9#pullrequestreview-1346958866_

**Comment by gkellogg** [comment]
This is an odd issue, and You have another similar comment on a PR from 2011: https://github.com/ruby-rdf/rdf-n3/pull/9#pullrequestreview-1346958866. Productive conversations are fine, noise is not.
